### ISSUE TITLE
Add working dir folder to GUI

### ISSUE THREAD

**Issue by davbeek** [davbeek/gitinspectorgui#20]
The Input folder path in the GUI requires an absolute path, which leads to long input and output paths.

To reduce the length of these paths and make the GUI more similar to the CLI, I propose to change the title of Input folder path to "Working dir" and to add an additional input box below it, titled "Input pattern", which can deal with (comma separated) `fnmatch` patterns from issue #19.

**Comment by Alberth289346** [comment]
Stick these paths in a configuration file? I assume directory structures used for checking aren't moving much. That means these paths are stable too then.

**Comment by davbeek** [comment]
Interesting idea, but I can imagine it could confuse users. Also I like the just implemented fnmatch for pattern matching. This means we now have pattern matching using `*, ?, []` also for the input path in the GUI and it works nicely. For now, I actually think that could be sufficient, so I am inclined to keep things as they are and not implement idea raised in this issue.

**Comment by davbeek** [comment]
I will close the issue. It is probably not worth the effort, it adds additional complexity and the added globbing in the GUI input folder path works well.
