### ISSUE TITLE
Update height of GUI window in Windows

### ISSUE THREAD

**Issue by davbeek** [davbeek/gitinspectorgui#26]
I always update the height of the window for macOS when new rows are added to the window. The height should also be adjusted for Windows.

**Comment by Alberth289346** [comment]
Just open it at a large size?

I assume it can handle having more space than needed :)

**Comment by davbeek** [comment]
The problem is the pysimplegui does not properly handle the distribution of the heights between the top settings frame height and the bottom console frame height. If the height of the top frame is too large, you get an ugly bar of white space below it, and if the height is set too small, you will always get a scrolling sidebar for the top frame, no matter how much you increase overal window size.

**Comment by Alberth289346** [comment]
Maybe pysimplegui is becoming a bit too simple?

This is a common problem with "simple" things. Quick to get started and experiment what you want to have. However, there usually isn't a good path to "beyond" what they provide.

I have no idea what exists nowadays for cross-platform support. Python itself has tkinter. It exists a few decades already, no idea of its current state.

My GUIs are trivial, basically a flat area, and I draw everything. Written in PyGame. Likely too simple for this application.

**Comment by davbeek** [comment]
Indeed, see issue #3 to add DearPyGUI as an alternative GUI to PySimpleGUI.

**Comment by davbeek** [comment]
Also note that Tkinter is still alive and kicking. PySimpleGUI translates to several backends, including tkinter. Tkinter itself however, is very low-level and not suitable for us.

**Comment by davbeek** [comment]
Fixed, closing.
