### ISSUE TITLE
Blame history should follow file renaming and creation

### ISSUE THREAD

**Issue by davbeek** [davbeek/gitinspectorgui#36]
Blame can follow file renaming and creation via the `---copy-move` (`-C`) option. Blame history (`--blame-history`) should always follow file copying, renaming and creation. If currently stops at all these events.

**Comment by Alberth289346** [comment]
It may happen if different members of a group each have the same file and rename it or change it in the same way in the same commit.

Not something that is likely to happen.

Alternatively, it may happen in larger file collections, where you have administrative files or config files that are all the same in different directories and you rename those directories.

**Comment by davbeek** [comment]
Fixed. The commits for the blame history option are now obtained via the fstr2fstat dictionary used to output the output table Files.
