### ISSUE TITLE
Investigate using a Flask webserver to dynamically generate a single required html page on demand

### ISSUE THREAD

**Issue by davbeek** [davbeek/gitinspectorgui#42]
In python, for html output using option `--blame-history`, we have a symbolic representation of the needed k files per repository, each with say n blame tables, one per commit, which gives a total of k * n blame tables. All those blame tables are generated into one large html file, but only one of the blame tables is shown using javascript, by hiding all others. 

We should also try to have python running a Flask webserver and let python generate only one table on demand so that not all tables that could ever be required need to be generated in advance in html. According to Copilot this can be done, also using pyinstaller to generate a macOS app or Windows executable.

Potential advantages are clear: much faster generation of the first required web page output and much smaller output files. E.g. for the current state of this repository, using option `--blame-history`, we get an html output file of 38MB generated in 19s. Without option `--blame-history`, file size is 3MB generated in 2.5s.

**Comment by davbeek** [comment]
Note that without option `--blame-history`, we only need to generate a single html blame table per required repository file + 4 tables for the stat file output. This works fine.

**Comment by davbeek** [comment]
Instead of Flask (4MB dependencies, wider range of features), also consider Bottle (0.07MB dependencies, minimalistic but probably more than enough for our simple use case). Both are very easy to setup.

**Comment by Alberth289346** [comment]
Bottle sounds familiar, I once wrote a translation website with that. It's still running :)

**Comment by davbeek** [comment]
Had some problems with Bottle that Copilot could now solve. Switched to Flask and it now works. Closing.
