### ISSUE TITLE
Use the pygit2 library instead of GitPython for interaction with git

### ISSUE THREAD

**Issue by Alberth289346** [davbeek/gitinspectorgui#53]
Git has machine readable output forms, but they don't seem used.

eg in `repo_reader.py` I read (around line 313):
``` python
            if "=>" not in line:
                # if no renames or copies have been found, the line represents the file
                # name fstr
                fstr = line
            elif "{" in line:
                # If { is in the line, it is part of a {...} abbreviation in a rename or
                # copy expression. This means that the file has been renamed or copied
                # to a new name. Set fstr to this new name.
                #
                # To find the new name, the {...} abbreviation part of the line needs to
                # be eliminated. Examples of such lines are:
                #
                # 1. gitinspector/{gitinspect_gui.py => gitinspector_gui.py}
                # 2. src/gigui/{ => gi}/gitinspector.py

                prefix, rest = line.split("{")

                # _ is old_part
                _, rest = rest.split(" => ")

                new_part, suffix = rest.split("}")
```
This is fragile. A filename like `x=>y` is quite trivially produced (`touch x=\>y`), filenames with curly braces and spaces can exist too.

Instead of relying on a user to produce non-conflicting filenames, use the machine readable output form (`-p` or `--porcelain` for `git log` or `git blame`, there is also `--line-porcelain`).

----

For the above code fragment, a regular expression is generally recommended so you get the entire pattern, including eg a space character at the start or end of a filename like `" my_file  "`:
``` python
>>> s = "gitinspector/{gitinspect_gui.py => gitinspector_gui.py}"
>>> import re
>>> pat = re.compile(r"\{(.*) => (.*)\}")

>>> m  = pat.search(s)
>>> m
<re.Match object; span=(13, 55), match='{gitinspect_gui.py => gitinspector_gui.py}'>
>>> m.groups()
('gitinspect_gui.py', 'gitinspector_gui.py')

>>> s = "src/gigui/{ => gi}/gitinspector.py"
>>> m  = pat.search(s)
>>> m
<re.Match object; span=(10, 18), match='{ => gi}'>
>>> m.groups()
('', 'gi')
```

If you don't want to use an RE, `split does have an optional max matching count, to avoid getting 2 or more matches.

**Comment by Alberth289346** [comment]
Path concatenation should be done with `os.path` instead of string manipulations.

To handle the possible `}/` that causes the `//` you can extend the pattern with `[\\/]?` which matches `/` or `\` so it gets discarded together with the `}`

**Comment by davbeek** [comment]
Machine readable output forms using the porcelain options are definitely preferable. I had read about them, but never realised that I could/should actually use them. Will have to look into that in more detail.

**Comment by Alberth289346** [comment]
I wonder if directly interfacing with git makes sense for this application (that is, eliminate the intermediate text stream). It seems to use git intensively, attaching git as a library to this application would probably speed up the transfer.

Eg `libgit` exists:
``` sh
$ apt show libgit2-1.7/noble

Package: libgit2-1.7
Version: 1.7.2+ds-1ubuntu3
Priority: optional
Section: libs
Source: libgit2
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Utkarsh Gupta <utkarsh@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 1,267 kB
Depends: libc6 (>= 2.38), libgssapi-krb5-2 (>= 1.17), libhttp-parser2.9 (>= 2.1), libpcre2-8-0 (>= 10.22), libssh2-1 (>= 1.7.0), libssl3 (>= 3.0.0), zlib1g (>= 1:1.1.4)
Homepage: https://libgit2.github.com/
Task: kubuntu-desktop, ubuntustudio-desktop-core, ubuntustudio-desktop, edubuntu-desktop-gnome, edubuntu-desktop-gnome-raspi
Download-Size: 529 kB
APT-Manual-Installed: no
APT-Sources: http://ftp.tudelft.nl/archive.ubuntu.com noble/main amd64 Packages
Description: low-level Git library
 libgit2 is a portable, pure C implementation of the Git
 distributed version control system core methods provided as a
 re-entrant link-able library with a solid API.
```

No idea if that is easily possible, it may involve some C-Python interfacing work, although I wouldn't be surprised if someone has done that already.  [Yep, that exists too:]
``` sh
$ apt show python3-git

Package: python3-git
Version: 3.1.37-3
Priority: optional
Section: universe/python
Source: python-git
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Python Team <team+python@tracker.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 669 kB
Depends: git, python3-gitdb, python3-typing-extensions | python3-supported-min (>= 3.8), python3:any
Suggests: python-git-doc
Homepage: https://github.com/gitpython-developers/GitPython
Download-Size: 138 kB
APT-Sources: http://ftp.tudelft.nl/archive.ubuntu.com noble/universe amd64 Packages
Description: Python library to interact with Git repositories
 The GitPython project provides object model access to a Git repository, so
 Python can be used to manipulate it. Repository objects can be opened or
 created, which can then be traversed to find parent commit(s), trees, blobs,
 etc.
 .
 This package provides the Python 3.x module.
```

**Comment by davbeek** [comment]
If that would work it would be really great! Now we require the user to have git or install git, which is rather cumbersome on macOS and on Windows. Will try it after having graded 170 students for the final assignment.

**Comment by davbeek** [comment]
[python3-git](url) is the Debian and Ubuntu version of [GitPython](https://github.com/gitpython-developers/GitPython) that we currently use. For interfacing with libgit2 we can use [pygit2](url).

**Comment by davbeek** [comment]
Unfortunately, not all git commands are directly available via `pygit2`. From Copilot:

Question:
Give the `pygit2` equivalent of `git log --follow file`:

Answer:
The `--follow` option in `git log` is used to follow renames when listing the history of a file. Unfortunately, `pygit2` does not have a direct equivalent for the `--follow` option. However, you can manually follow renames by inspecting the commit history and checking for renames.

Here is an example of how you can achieve this using `pygit2`:
<img width="585" alt="image" src="https://github.com/user-attachments/assets/95b19f9b-f399-45c3-a808-115ef07b6d4a">

**Comment by davbeek** [comment]
Given that rewriting the code to use `pygit2` instead of `GitPython` is not trivial, I will change the Milestone from 0.4.0 to 0.5.0

**Comment by Alberth289346** [comment]
Makes sense. Gits' primary goal is compact data storage with unique identifiers, such that they can be exchanged between repsitories. Extracting useful information like history of files is not core business.

In other words, such things are computed on the fly, likely in the same way as you need to do in pygit2

**Comment by davbeek** [comment]
This is such important functionality that I have changed the milestone to 0.4.0.

**Comment by davbeek** [comment]
Done. To implement the blame calculations using pygit2, I also improved the implementation by restructuring the modules blamereader, reporeader and repo, and renamed them so that they now all inherit from the same base class RepoBase.

The only remaining problem is that `pygit2` does not yet implement move or copy detection corresponding to the git options `-M` and (multiples of) `-C`.

The implementation of module `enums` in pygit2 writes:
```
class BlameFlag(IntFlag):
    NORMAL = _pygit2.GIT_BLAME_NORMAL
    'Normal blame, the default'

    TRACK_COPIES_SAME_FILE = _pygit2.GIT_BLAME_TRACK_COPIES_SAME_FILE
    'Not yet implemented and reserved for future use (as of libgit2 1.8.0).'

    TRACK_COPIES_SAME_COMMIT_MOVES = _pygit2.GIT_BLAME_TRACK_COPIES_SAME_COMMIT_MOVES
    'Not yet implemented and reserved for future use (as of libgit2 1.8.0).'

    TRACK_COPIES_SAME_COMMIT_COPIES = _pygit2.GIT_BLAME_TRACK_COPIES_SAME_COMMIT_COPIES
    'Not yet implemented and reserved for future use (as of libgit2 1.8.0).'

    TRACK_COPIES_ANY_COMMIT_COPIES = _pygit2.GIT_BLAME_TRACK_COPIES_ANY_COMMIT_COPIES
    'Not yet implemented and reserved for future use (as of libgit2 1.8.0).'
```
and although the current version of libgit2 is already at `1.8.4`,  the above mentioned `TRACK_COPIES_...` options are all ignored and the implementation is equivalent to the GitPyhtion implementation corresponding to `--copy-move 0`, so no copy-move detection.

**Comment by davbeek** [comment]
I found some more troublesome info about the blame implementation of `pygit2`, which apparently is unexpectedly slow and immature:
- https://github.com/libgit2/libgit2/issues/3027
- https://github.com/aspiers/git-deps/issues/1
- https://github.com/aspiers/git-deps/pull/127

Therefore, it looks like using the `pygit2` blame implementation is not a good idea. The question now is whether we do use it only for the stats tables and use GitPython for blame calculations or eliminate pygit2 completely.

**Comment by davbeek** [comment]
Even more troublesome is that GitKraken started off using `pygit2`, see https://staging-www.gitkraken.com/blog/nodegit-libgit2, and is now migrating to the bundled git executable, see https://www.gitkraken.com/blog/gitkraken-client-migrating-from-libgit2-to-git-executable.

In fact, I have enable this feature in the Experimental Features section of the GitKraken preferences:
<img width="723" alt="image" src="https://github.com/user-attachments/assets/fb6f68fe-c7b9-4b7a-a656-2edfba8fc036" />

So GitKraken has solved the git dependency problem by bundling the git executable.

**Comment by davbeek** [comment]
We could update our "old" gitpython implementation with the new inheritance features implemented when I switched to pygit2 and then also switch to using the porcelain git commands as much as possible.

**Comment by davbeek** [comment]
In addition, pygit2 lacks an option to exclude commits (revisions) for blame calculations.

**Comment by Alberth289346** [comment]
It's all complicated, apparently. I don't know enough to make much sense of what is said, unfortunately.

**Comment by davbeek** [comment]
My conclusion is that we should get back to the GitPython implementation, keeping the improved inheritance structure and switching to porcelain command as much as possible . I will make new issues for that. Closing this.

**Comment by davbeek** [comment]
As a note to https://github.com/davbeek/gitinspectorgui/issues/53#issue-2664134123, where @Alberth289346 pointed to the `--porcelain` option, I can report that in fixing issue #112, I used the `--porcelain` option for `git blame -follow`, which works very nicely. For `git log --follow`, however, there is no option `--porcelain` available.
