### ISSUE TITLE
Change blame code buttons to act globally

### ISSUE THREAD

**Issue by davbeek** [davbeek/gitinspectorgui#60]
The buttons in the Code column of the blame sheets have a local state per blame history table. We should change this to a more global state, because I have noticed while grading, that when I change the state of one of the blame history tables, I often want to see the same change in other blame history tables. If you only want to see a local change, it is easy to toggle the button a second time to leave the global state unchanged.

The only question is how global the states should be. It could be per blame file or even globally for all blame files. We should start with keeping the state locally per blame file and see if that works.

**Comment by Alberth289346** [comment]
It's probably also useful to do this to have a consistent view over all sheets.

I can imagine one doesn't want to remember these toggle states while checking all the results.

**Comment by davbeek** [comment]
Then we will probably need an additional row for the three buttons, so that they are no longer locally in the header of each table. This will require an additional row for the buttons in the html output, just above each table, but that is probably worth it for the improved clarity and easy of use.

**Comment by davbeek** [comment]
As alternative, we could keep the header row static in the case of blame history, loading only the table body dynamically for each radio commit button. This would be an easy way of keeping the states of the three buttons when dynamically loading another blame history table.

In this way, we would not need an additional row for the three buttons, which can stay nicely in the Code header column that has more than enough space.

The problem with this is that it would not work for static blame history, where all tables are always present and only one of the tables is visualised with all other tables hidden.

**Comment by davbeek** [comment]
Done, by storing the state of the buttons globally in javascript. Closing.
