### ISSUE TITLE
Add option to show only absolute stats

### ISSUE THREAD

**Issue by davbeek** [davbeek/gitinspectorgui#65]
When checking correctness of results, only the absolute numbers are relevant, therefore it would be clearer if the columns % Lines and % Insertions would be removed / hidden from the output.

**Comment by Alberth289346** [comment]
blank them?

**Comment by davbeek** [comment]
I would have liked to have them when testing, but now that the problem has been solved, I am left wondering if it is worth adding yet another option.

**Comment by davbeek** [comment]
Now that the problems have been fixed, I am going to close this issue. If needed, we can reopen it later, but for now, I don't like adding yet another option.

**Comment by davbeek** [comment]
The problem has been solved by positioning the columns with absolute values before the columns with percentages. This appears to be a better order in all cases.
