### ISSUE TITLE
Saving settings via GUI sets multi-threading

### ISSUE THREAD

**Issue by davbeek** [davbeek/gitinspectorgui#70]
Because the GUI is set to always use multi-threading, saving the settings via the GUI always sets `--multi-threading`, even if it was set to `--no-multi-threading`.

**Comment by Alberth289346** [comment]
Either the flagname is wrong, or I don't see the point of a setting that is just ignored :)

**Comment by davbeek** [comment]
I have added a `multi-threading` checkbox to the GUI. Now things work as expected. Closing.
