### ISSUE TITLE
multi-threading can lead to deadlock

### ISSUE THREAD

**Issue by davbeek** [davbeek/gitinspectorgui#71]
When multi-threading is on and `--n-files` is set to 5 or bigger for the gitinspectorgui repo, deadlock can occur.

**Comment by Alberth289346** [comment]
`5` likely has nothing to do with it other than having sufficient concurrent attempts to create an occurrence.

**Comment by davbeek** [comment]
I have added a threading lock for repo access via the GitPython git.log command. This avoids the deadlock. 

For blame access via GitPython I have not added a threading lock. Doing so caused execution time of gitinspectorgui for all files to remain at 4.0s regardless of using multi-threading. Without the threading lock, using multi-threading reduced the execution time from 4s to 2.8s.

Closing.

**Comment by Alberth289346** [comment]
It's a bit weird that logging causes deadlock. Basically you're reading information, so you wouldn't expect problems there, at first sight.

Did you check that gitpython is multi-threading safe? In 2021 it wasn't, see https://github.com/gitpython-developers/GitPython/issues/1128#issuecomment-782144878
The created discussion there didn't have any new information beyond "it's not thread-safe".

Thread-safety is also be required for git too. Reading will probably work, as stated in https://stackoverflow.com/questions/57897153/is-a-local-git-repository-thread-safe#57897504
Modifying the working tree isn't at least, but that's to be expected.

A relatively simple way out seems to be to move gitpython usage to several child-processes instead of threads. Eg with https://docs.python.org/3/library/multiprocessing.html
As you have a full process, you may want to do any post-processing in that process as well (probably like you're doing now already).

**Comment by Alberth289346** [comment]
Hmm, a caveat with that library. First line:
```
[Availability](https://docs.python.org/3/library/intro.html#availability): not Android, not iOS, not WASI.
```

**Comment by Alberth289346** [comment]
Other options:

- Accept the 1.2 seconds delay. To me, risk of deadlock / incorrect result is not worth 1.2 seconds waiting.
- Take out gitpython (but you've been there, so probably not an option).
- Improve gitpython (may not be trivial to achieve).
- Store previous found results in a cache-file or data-base, so it can be re-used between invocations of the tool.
- Rethink when to do processing. Currently you are waiting for the user to tell you what to do, but there is no reason why that must be done in that way. Commonly needed information can be queried and processed immediately after startup, and then saved in case the user needs it.
- If you're not doing this already, gitpython access is probably the bottleneck, so only protect that with a mutex. Anything before or after it should be done without blocking gitpython usage by other threads.

**Comment by davbeek** [comment]
> Did you check that gitpython is multi-threading safe? In 2021 it wasn't, see
> https://github.com/gitpython-developers/GitPython/issues/1128#issuecomment-782144878

Interesting, in that comment:
> GitPython is not thread safe, and each thread must own its own instance of a Repo while only performing read operations on them.

We are only performing read operations, but the threads are sharing their Repo instance, so that could still be improved.

**Comment by davbeek** [comment]
I don't see how that is a problem, as gitinspectorgui only runs on desktops, not on mobile.

> Hmm, a caveat with that library. First line:
> 
> ```
> [Availability](https://docs.python.org/3/library/intro.html#availability): not Android, not iOS, not WASI.
> ```

I don't see how that is a problem, as gitinspectorgui only runs on desktops, not on mobile.

**Comment by davbeek** [comment]
> Accept the 1.2 seconds delay. To me, risk of deadlock / incorrect result is not worth 1.2 seconds waiting.

For bigger repos, the difference is also bigger: Execution time for the main repo for the website went from 43.3s without multi-threading to 23.8 with multi-threading, so a reduction from 100% to 55%, even with a threading lock for repository access for the git log commands via GitPython., see https://github.com/davbeek/gitinspectorgui/issues/38#issuecomment-2563105093

**Comment by davbeek** [comment]
> A relatively simple way out seems to be to move gitpython usage to several child-processes instead of threads. Eg with https://docs.python.org/3/library/multiprocessing.html
> As you have a full process, you may want to do any post-processing in that process as well (probably like you're doing now already).

I will look into that.

**Comment by Alberth289346** [comment]
> I don't see how that is a problem, as gitinspectorgui only runs on desktops, not on mobile.

I wasn't sure what 'iOS' means, but if it's not desktops, great!
`multiprocessing` is a valid option then, like you concluded.

**Comment by davbeek** [comment]
iOS is the operating system of Apple smartphones and was the operating system of iPads (Apple tablets). A few years ago, iPads got the own operating system: iPadOS.

**Comment by Alberth289346** [comment]
> We are only performing read operations only, but the threads are sharing their Repo instance, so that could still be improved.

Cloning at the local file system is cheap and fast. At my system it shares the stable repo data files by adding a link to it.

I never do a shallow clone since I want to work with the files. Not sure if that would be a feasible option for gitinspector.

**Comment by davbeek** [comment]
I removed the threading lock and created a new GitPython repo for each thread. This appears to work and is a much nicer solution: robust but without the waiting times that may be associated with threading locks. Closing.
